## Stretch Exercise: Number Guessing Game

'''
Building on the Python code asking for a message and then printing it again, 
write a program that asks the user to guess a number between 1 and 10. 
The program then prints whether the number is equal to the random number generated by the code. 
So it then prints `True` and ends the program if the input number is equal to the random number.
If it is not equal to the number generated by the code, it prints `False` and ends the program.
As a starting point, try writing code to match this pseudocode (a mix between natural language and generic technical language):

    1. Prompt user for input
    2. Generate a random number
    3. Compare generated number to input
    4. Print result
'''

import random as r

# Step 1: Prompt user for input
user_guess = int(input("Guess a number between 1 and 10: "))

# Step 2: Generate a random number
random_number = r.randint(1, 10)

# Step 3: Compare generated number to input
is_correct = user_guess == random_number

# Step 4: Print result
print(f"Your guess: {user_guess}")
print(f"Random number: {random_number}")
print(f"Result: {is_correct}")
